### ISSUE TITLE
Some problems

### ISSUE THREAD

**Issue by kevlik** [VinylNerd/ThinkPad-T440P-OpenCore#13]
Hello, sorry for my English
I have 3 problems
1. My touchpad works, but when I use the physical buttons, the cursor freezes very much and 2-finger scrolling stops working. (Right now I'm using the touchpad, not the clickpad, it works fine.)
2. When I press a button on the keyboard, the touchpad stops responding for a second, very annoying.
3. Microphone sound is noisy. Continuously records background noises.

Help pls

**Comment by VinylNerd** [comment]
@kevlik 

1. could you please clarify exactly which trackpad/touchpad you have? if you have numerous could you specify which features are working with each

i dont own a Stock T440P touchpad anymore, but i do own 2 T450 touchpads with the 3 buttons, i have an ALPS and a Synaptics

the current released build only works good for ALPS trackads, Synaptics will be supported on the next build i plan to release shortly. just need to test

2. not sure why this would be, hopefully also fixed with next build, i dont have this issue

3. microphone quality is not great but it works for me, i just tested on a whataspp audio call and was able to talk to the person totaly fine but they tell me that there is some background noise yes, it sounds to me like the microphone picks up the fan somehow, maybe possible threre is multiple microphones including one on the camera and can be sorted, but this issue is currently very low priority for me as i almost never use the mic personally

**Comment by kevlik** [comment]
https://imgur.com/xsYSqd2
synaptic clickpad
https://drive.google.com/drive/folders/1OJI8lfxUTbmU9IJMuKQuNEGJSzFVkUta?usp=sharing
trackpad works perfect

**Comment by CoderKe** [comment]
When will the Monterey EFI be released

**Comment by VinylNerd** [comment]
@kevlik try this release

https://github.com/VinylNerd/ThinkPad-T440P-OpenCore/releases/tag/v0.6-beta1

@CoderKe personally i'm waiting for drivers for my DJ mixer (DJM900NXS) as i need it to be able to connect to my computer, it took Pioneer untill Feb 2021 to release drivers for Big Sur so im expecting 1-3 more months before i can make the switch.

**Comment by kevlik** [comment]
Everything worked. Thanks a lot.

**Comment by VinylNerd** [comment]
thanks :), closing this issue now.

build is almost as stable as it can get. 

i am now confident this is the best T440P repo for hackintoshing on OpenCore and Big Sur.

over the coming months i will be looking into and testing monteray and will keep this repo updated with each new release of opencore and components, cheers all for helping me get this far.
